GET http://localhost:3000/init-data

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "lisi",
  "password": "123456"
}

### 查看文章
GET http://localhost:3000/article/1

### 记录浏览文章次数
GET http://localhost:3000/article/2/views
Cookie: connect.sid=s%3AdGZFC5vwQdgmoCe-yIfKdShz9WP_lvlq.174gNhdT6I2lkymOSow9UB4vT1ss180w50%2BtGwGEBxw; Path=/; HttpOnly
